/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Exact tokens from Stitch "High-Performance Discipline" design HTML
        'on-primary-fixed-variant': '#783200',
        'on-surface-variant': '#e0c0b1',
        'inverse-on-surface': '#303036',
        'on-secondary': '#3c0091',
        'tertiary-fixed': '#6bff8f',
        'surface-container': '#1f1f25',
        'on-background': '#e4e1e9',
        'inverse-primary': '#9d4300',
        'tertiary-container': '#00b251',
        'surface-container-lowest': '#0e0e13',
        'surface': '#131318',
        'on-primary': '#552100',
        'primary-fixed': '#ffdbca',
        'inverse-surface': '#e4e1e9',
        'outline-variant': '#584237',
        'on-tertiary': '#003915',
        'surface-dim': '#131318',
        'surface-tint': '#ffb690',
        'on-secondary-container': '#c4abff',
        'surface-container-high': '#2a292f',
        'error-container': '#93000a',
        'on-secondary-fixed-variant': '#5516be',
        'on-secondary-fixed': '#23005c',
        'surface-bright': '#39383e',
        'secondary-container': '#571bc1',
        'secondary': '#d0bcff',
        'on-tertiary-container': '#003b16',
        'secondary-fixed-dim': '#d0bcff',
        'on-surface': '#e4e1e9',
        'background': '#131318',
        'on-tertiary-fixed': '#002109',
        'on-primary-container': '#582200',
        'error': '#ffb4ab',
        'secondary-fixed': '#e9ddff',
        'primary': '#ffb690',
        'surface-container-low': '#1b1b20',
        'primary-fixed-dim': '#ffb690',
        'on-tertiary-fixed-variant': '#005321',
        'surface-container-highest': '#35343a',
        'tertiary-fixed-dim': '#4ae176',
        'outline': '#a78b7d',
        'primary-container': '#f97316',
        'on-error-container': '#ffdad6',
        'tertiary': '#4ae176',
        'surface-variant': '#35343a',
        'on-primary-fixed': '#341100',
        'on-error': '#690005',
        // Legacy aliases
        'base': '#131318',
        'elevated': '#2a292f',
        'border': '#584237',
        'accent': '#ffb690',
        'muted': '#e0c0b1',
        'success': '#4ae176',
        'violet': '#d0bcff',
      },
      fontFamily: {
        headline: ['Inter'],
        body: ['Inter'],
        label: ['Inter'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      animation: {
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'fade-in': 'fade-in 0.3s ease-out',
        'slide-up': 'slide-up 0.4s cubic-bezier(0.19, 1, 0.22, 1)',
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 8px rgba(249,115,22,0.4)' },
          '50%': { boxShadow: '0 0 24px rgba(249,115,22,0.8)' },
        },
        'fade-in': {
          from: { opacity: 0 },
          to: { opacity: 1 },
        },
        'slide-up': {
          from: { opacity: 0, transform: 'translateY(12px)' },
          to: { opacity: 1, transform: 'translateY(0)' },
        },
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.19, 1, 0.22, 1)',
      },
    },
  },
  plugins: [],
};
